export default {
	herme: {
		image: '',
		name: 'Herme.io',
		description: 'Application web de réseau social',
		tech: 'Node.js, ReactJS, PostgreSQL',
		features: [
			'Création et suppression de publications',
			'Ajouter des amis',
			'Voir les publications des amis',
			'Liker les publications des amis'],
		source: 'https://www.github.com/adxl/herme.io',
		demo: 'https://adxl.github.io/herme.io',
	},
	wtracker: {
		image: '',
		name: 'Weight Tracker',
		description: 'Application web permettant le suivi de poids corporel',
		tech: 'Spring, ReactJS, MongoDB',
		features: [
			'Authentification de l\'utilisateur',
			'Chaque entrée a sa date correspondante',
			'Représentation visuelle des données dans un graphique',
			'Exportation des données au format JSON'],
		source: 'https://www.github.com/adxl/Weight-Tracker',
		demo: null,
	},
	life: {
		image: '',
		name: 'Life',
		description: 'Implémentation de l\'automate cellulaire de Conway',
		tech: 'ReactJS, P5.js',
		features: [
			'Taille de grille personnalisable',
			'Possibilité de limiter les générations',
			'Cellules carrées ou circulaires',
			'Animation fluide'],
		source: 'https://www.github.com/adxl/Life',
		demo: 'https://adxl.github.io/life',
	},
	knights: {
		image: '',
		name: 'Knights',
		description: 'Casse-tête basé sur les échecs',
		tech: 'ReactJS, P5.js',
		features: [
			'Règles du jeu en français et en anglais',
			'Possibilité d\'activer les indices',
			'Compteur de coups et score final à la fin',
			'Hébergé sur Pages et accessible en ligne'],
		source: 'https://www.github.com/adxl/knights',
		demo: 'https://adxl.github.io/knights',
	},
	webuy: {
		image: '',
		name: 'WeBuy',
		description: 'Application web de E-commerce',
		tech: 'HTML/CSS, JavaScript (jQuery), Spring, MongoDB',
		features: [
			'Gestion du panier',
			'Aperçu des commandes',
			' Portefeuilles virtuel rechargeable',
			'Plusieurs rôles d\'administrateurs',
			'Gestion de stock',
			'Factures imprimables',
		],
		source: null,
		demo: null,
	},
	forum: {
		image: '',
		name: 'Forum',
		description: 'Forum de discussions anonyme',
		tech: 'AngularJS, Spring, MySQL',
		features: [
			'Aucune inscription requise',
			'Possibilité de trier les questions par date ou nombre de réponses',
			'Passage à une question aléatoire',
			''],
		source: 'https://www.github.com/adxl/forum',
		demo: null,
	},
};
